name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16.10"
          cache: "npm"
      - name: Install dependencies
        run: npm install

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16.10"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test

  scan:
    needs: build
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: wongshennan/test_repository
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .
      - name: Run Snyk container scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_NAME }}
          fail-on-issues: true
          severity-threshold: high

  codescan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16.10"
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run Snyk code scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  publish:
    needs: [test, scan, codescan]
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: wongshennan/test_repository
    steps:
      - uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

  deploy:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "shennan-su-devops"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
      - name: Deploy to Heroku
        run: |
          heroku container:login
          heroku stack:set container -a shennan-su-devops
          heroku container:push web -a shennan-su-devops
          heroku container:release web -a shennan-su-devops
